-- stills coarse scale annotations remove the comment self stuff and % for Soleosmilia matrix

DROP VIEW VW_STILLS_VME;
CREATE VIEW VW_STILLS_VME AS SELECT
    T2.SURVEY_OPS,
	T1.CONCEPT,
    REPLACE(REPLACE(REPLACE(T1.ASSOCIATIONS,' |  | ',''),'comment | self | ',''),'%','') AS CNT,  -- remove the unnecessary string bits from the association field leaving only the count number, % for solenosmilia atrix comment 
    T1.IMAGED_MOMENT_UUID,
    cast(T1.INDEX_RECORDED_TIMESTAMP as timestamp(0)) AS REC_TIME_TAG1S,
    T1.INDEX_TIMECODE,
    T1.OBSERVATION_UUID,
    T1.ACTIVITY,
    T1.OBSERVER,
    T1.IMAGE_REFERENCE_UUID,
    T1.IMAGE_DESCRIPTION,
    T1.IMAGE_URL,
    T1.ALTITUDE,
    T1.DEPTH_METERS,
    T1.LATITUDE,
    T1.LONGITUDE,
    T1.VIDEO_NAME,
    T1.CAMERA_DEPLOYMENT_ID
FROM
    VARS2018.ANNOTATIONS T1
INNER JOIN
    BHIMAGE.VW_VARS_VIDEOS T2
ON
    (
        T1.VIDEO_NAME = T2.VIDEO_NAME)
WHERE
	T1.ACTIVITY LIKE 'stills_coarse'
AND
	T1.IMAGE_DESCRIPTION LIKE 'Q%'   -- ONLY EXTRACT DATA FOR QUADRATS (CAREFUL IF ANNOTATING FOR IMAGES WHERE NO QUADRAT HAS BEEN REGISTERED YET...) note otherwise get triplicates of each record!
;



-- CREATE TABLE OF THE EXTRACT FOR FURTHER MANIPULATION
DROP TABLE TB_IN2018_V06_STILLS_VME;
CREATE TABLE TB_IN2018_V06_STILLS_VME AS
SELECT	*
FROM
	 BHIMAGE.VW_STILLS_VME
;


@export on;
@export set filename="C:\Data\2018_SeamountSurvey\data\IN2018_V06\Imagery\AllDataExtract\IN2018_V06_STILLS_VME_20190717.csv" format="csv" CsvColumnDelimiter=",";
-- select path and file name for output that works for you and increase Max Row for output

SELECT 
        *
FROM
       BHIMAGE.VW_STILLS_VME
 ; 

@export off;


-- GET VIDEO LAT-LONG ATTACHED TO STILLS & SUMARY 1 REC PER IMAGE
DROP VIEW VW_STILLS_VME_LOC;
CREATE VIEW VW_STILLS_VME_LOC AS SELECT
    T1.SURVEY_OPS,
    T1.REC_TIME_TAG1S,
    T1.IMAGE_DESCRIPTION,
    T1.IMAGE_URL,
    T2.CAM_LONG,
    T2.CAM_LAT,
    T2.DPTH_M,
    T2.IMAGE_KEY,
    COUNT(T1.CONCEPT) AS CNT_VMEANNO
FROM
    BHIMAGE.VW_STILLS_VME T1
INNER JOIN
    BHIMAGE.TB_IN2018_V06_VIDEOANNO_20190717 T2
ON
    (
        T1.REC_TIME_TAG1S =
        T2.REC_TIMESTAMP)
GROUP BY
    T1.SURVEY_OPS,
    T1.REC_TIME_TAG1S,
    T1.IMAGE_DESCRIPTION,
    T1.IMAGE_URL,
    T2.CAM_LONG,
    T2.CAM_LAT,
    T2.DPTH_M,
    T2.IMAGE_KEY ;
	
	@export on;
@export set filename="C:\Data\2018_SeamountSurvey\data\IN2018_V06\Imagery\AllDataExtract\IN2018_V06_STILLS_VME_LOC_20190717.csv" format="csv" CsvColumnDelimiter=",";
-- select path and file name for output that works for you and increase Max Row for output

SELECT 
        *
FROM
       VW_STILLS_VME_LOC
 ; 

@export off;

--MISCELLANEOUS
--extract - octocoral records
@export on;
@export set filename="C:\Data\2018_SeamountSurvey\data\IN2018_V06\Imagery\AllDataExtract\STILLS_VME_Octos20190826.csv" format="csv" CsvColumnDelimiter=",";
-- select path and file name for output that works for you and increase Max Row for output
SELECT
    BHIMAGE.VW_STILLS_VME.SURVEY_OPS,
    BHIMAGE.VW_STILLS_VME.CONCEPT,
    SUM(BHIMAGE.VW_STILLS_VME.CNT),
    BHIMAGE.VW_STILLS_VME.IMAGE_DESCRIPTION,
    BHIMAGE.VW_STILLS_VME.IMAGE_URL,
    BHIMAGE.VW_STILLS_VME_LOC.CAM_LONG,
    BHIMAGE.VW_STILLS_VME_LOC.CAM_LAT,
    BHIMAGE.VW_STILLS_VME_LOC.DPTH_M,
    BHIMAGE.VW_STILLS_VME_LOC.IMAGE_KEY,
    BHIMAGE.VW_STILLS_VME_LOC.CNT_VMEANNO
FROM
    BHIMAGE.VW_STILLS_VME
INNER JOIN
    BHIMAGE.VW_STILLS_VME_LOC
ON
    (
        BHIMAGE.VW_STILLS_VME.IMAGE_URL = BHIMAGE.VW_STILLS_VME_LOC.IMAGE_URL)
WHERE
    BHIMAGE.VW_STILLS_VME.CONCEPT = 'Black & Octocorals'
GROUP BY
    BHIMAGE.VW_STILLS_VME.SURVEY_OPS,
    BHIMAGE.VW_STILLS_VME.CONCEPT,
    BHIMAGE.VW_STILLS_VME.IMAGE_DESCRIPTION,
    BHIMAGE.VW_STILLS_VME.IMAGE_URL,
    BHIMAGE.VW_STILLS_VME_LOC.CAM_LONG,
    BHIMAGE.VW_STILLS_VME_LOC.CAM_LAT,
    BHIMAGE.VW_STILLS_VME_LOC.DPTH_M,
    BHIMAGE.VW_STILLS_VME_LOC.IMAGE_KEY,
    BHIMAGE.VW_STILLS_VME_LOC.CNT_VMEANNO ;

@export off;